# Main colors
background            #131318
foreground            #e4e1e9
cursor                #e4e1e9
cursor_text_color     #131318
selection_background  #444559
selection_foreground  #e1e0f9
url_color             #e7b9d5

# ANSI colors
color0                #131318
color1                #ffb4ab
color2                #e7b9d5
color3                #c5c4dd
color4                #bec2ff
color5                #e7b9d5
color6                #c5c4dd
color7                #e4e1e9
color8                #46464f
color9                #93000a
color10               #5e3c53
color11               #444559
color12               #3d4279
color13               #444559
color14               #5e3c53
color15               #c7c5d0

# Starship prompt bubbles
color255              #3d4279
color254              #bec2ff
color253              #444559
color252              #c5c4dd
color251              #5e3c53
color250              #e7b9d5
color249              #93000a
color248              #ffb4ab
color232              #e0e0ff
color233              #262b61
color234              #e1e0f9
color235              #2e2f42
color236              #ffd7ee
color237              #45263c
color238              #ffdad6
color239              #690005
color240              #e0e0ff
color243              #bec2ff
color244              #ffb4ab
color245              #46464f

# UI elements
active_tab_foreground   #262b61
active_tab_background   #bec2ff
inactive_tab_foreground #e0e0ff
inactive_tab_background #3d4279
active_border_color     #bec2ff
inactive_border_color   #91909a

# Marks
mark1_foreground        #0f144b
mark1_background        #e0e0ff
mark2_foreground        #191a2c
mark2_background        #e1e0f9
mark3_foreground        #2e1126
mark3_background        #ffd7ee
