#!/opt/homebrew/bin/lua

-- Add the sketchybar module to the package cpath
package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

-- Add the config directory to the package path
package.path = package.path .. ";/Users/" .. os.getenv("USER") .. "/.config/sketchybar/?.lua"
package.path = package.path .. ";/Users/" .. os.getenv("USER") .. "/dotfiles/sketchybar/?.lua"

-- Load the sketchybar-package and prepare the helper binaries
require("init")
